# Generated by Django 4.1 on 2022-08-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.store'),
        ),
    ]
